// ─────────────────────────────────────────────────────────────────────────────
// SankalpQ — Instructor Mock Data
// Realistic quantum-education mock data for all instructor portal features.
// Architecture is service-abstracted → ready for real Supabase/FastAPI backend.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  StudentOverview,
  StudentDetail,
  StudentActivity,
  InstructorCourse,
  CircuitTemplate,
  InstructorChallenge,
  InstructorAssessment,
  InstructorQuizQuestion,
  Announcement,
  PlatformAnalytics,
  AIInsight,
} from './types'

// ── Mock Students ─────────────────────────────────────────────────────────────

export const MOCK_STUDENTS: StudentOverview[] = [
  {
    id: 'std-001',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@student.sankalpq.in',
    role: 'student',
    avatarInitials: 'AM',
    createdAt: '2026-06-15T09:00:00Z',
    lastActiveAt: '2026-09-01T14:23:00Z',
    overallProgress: 78,
    coursesCompleted: 3,
    lessonsCompleted: 24,
    challengesCompleted: 12,
    averageQuizScore: 82,
    learningStreak: 14,
    status: 'active',
    strongConcepts: ['Quantum Gates', 'Superposition', 'Measurement'],
    weakConcepts: ['Entanglement', 'Multi-Qubit Circuits', 'Bell States'],
  },
  {
    id: 'std-002',
    name: 'Priya Sharma',
    email: 'priya.sharma@student.sankalpq.in',
    role: 'student',
    avatarInitials: 'PS',
    createdAt: '2026-06-18T10:30:00Z',
    lastActiveAt: '2026-09-01T20:10:00Z',
    overallProgress: 91,
    coursesCompleted: 4,
    lessonsCompleted: 32,
    challengesCompleted: 18,
    averageQuizScore: 94,
    learningStreak: 21,
    status: 'active',
    strongConcepts: ['Superposition', 'Entanglement', 'Bell States', 'Quantum Gates'],
    weakConcepts: ["Grover's Algorithm"],
  },
  {
    id: 'std-003',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@student.sankalpq.in',
    role: 'student',
    avatarInitials: 'RG',
    createdAt: '2026-07-01T08:00:00Z',
    lastActiveAt: '2026-08-20T11:45:00Z',
    overallProgress: 42,
    coursesCompleted: 1,
    lessonsCompleted: 11,
    challengesCompleted: 4,
    averageQuizScore: 58,
    learningStreak: 2,
    status: 'needs-attention',
    strongConcepts: ['Quantum Fundamentals', 'Classical Bit vs Qubit'],
    weakConcepts: ['Superposition', 'Entanglement', 'Quantum Gates', 'CNOT Gate'],
  },
  {
    id: 'std-004',
    name: 'Kavya Nair',
    email: 'kavya.nair@student.sankalpq.in',
    role: 'student',
    avatarInitials: 'KN',
    createdAt: '2026-06-20T12:00:00Z',
    lastActiveAt: '2026-09-01T18:30:00Z',
    overallProgress: 85,
    coursesCompleted: 3,
    lessonsCompleted: 28,
    challengesCompleted: 15,
    averageQuizScore: 88,
    learningStreak: 17,
    status: 'active',
    strongConcepts: ['Superposition', 'Quantum Gates', 'Bell States', 'Entanglement'],
    weakConcepts: ['Quantum Error Correction', 'Phase Kickback'],
  },
  {
    id: 'std-005',
    name: 'Vikram Singh',
    email: 'vikram.singh@student.sankalpq.in',
    role: 'student',
    avatarInitials: 'VS',
    createdAt: '2026-07-10T14:00:00Z',
    lastActiveAt: '2026-08-05T09:00:00Z',
    overallProgress: 25,
    coursesCompleted: 0,
    lessonsCompleted: 6,
    challengesCompleted: 2,
    averageQuizScore: 41,
    learningStreak: 0,
    status: 'inactive',
    strongConcepts: ['Quantum Fundamentals'],
    weakConcepts: ['Superposition', 'Quantum Gates', 'Entanglement', 'Measurement', 'Bell States'],
  },
  {
    id: 'std-006',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@student.sankalpq.in',
    role: 'student',
    avatarInitials: 'AI',
    createdAt: '2026-06-12T11:00:00Z',
    lastActiveAt: '2026-09-01T22:00:00Z',
    overallProgress: 96,
    coursesCompleted: 5,
    lessonsCompleted: 38,
    challengesCompleted: 22,
    averageQuizScore: 97,
    learningStreak: 30,
    status: 'active',
    strongConcepts: ['All Concepts'],
    weakConcepts: [],
  },
  {
    id: 'std-007',
    name: 'Dev Patel',
    email: 'dev.patel@student.sankalpq.in',
    role: 'student',
    avatarInitials: 'DP',
    createdAt: '2026-07-05T10:00:00Z',
    lastActiveAt: '2026-08-28T16:20:00Z',
    overallProgress: 55,
    coursesCompleted: 2,
    lessonsCompleted: 16,
    challengesCompleted: 7,
    averageQuizScore: 67,
    learningStreak: 5,
    status: 'active',
    strongConcepts: ['Quantum Fundamentals', 'Superposition'],
    weakConcepts: ['Entanglement', 'Multi-Qubit Circuits', "Grover's Algorithm"],
  },
  {
    id: 'std-008',
    name: 'Meera Krishnan',
    email: 'meera.krishnan@student.sankalpq.in',
    role: 'student',
    avatarInitials: 'MK',
    createdAt: '2026-06-25T09:30:00Z',
    lastActiveAt: '2026-09-01T12:00:00Z',
    overallProgress: 72,
    coursesCompleted: 3,
    lessonsCompleted: 22,
    challengesCompleted: 10,
    averageQuizScore: 76,
    learningStreak: 9,
    status: 'active',
    strongConcepts: ['Quantum Gates', 'Measurement', 'Superposition'],
    weakConcepts: ['Bell States', 'CNOT Gate', 'Phase Kickback'],
  },
]

// ── Mock Student Details ──────────────────────────────────────────────────────

const ARJUN_ACTIVITIES: StudentActivity[] = [
  { id: 'act-001', studentId: 'std-001', type: 'lesson-complete', label: 'Completed Lesson', detail: 'Superposition & the Hadamard Gate', timestamp: '2026-09-01T14:23:00Z' },
  { id: 'act-002', studentId: 'std-001', type: 'circuit-built', label: 'Built Circuit', detail: 'Bell State — H + CNOT pattern', timestamp: '2026-08-31T10:12:00Z' },
  { id: 'act-003', studentId: 'std-001', type: 'challenge-attempt', label: 'Attempted Challenge', detail: 'Create a Bell State (score: 82%)', timestamp: '2026-08-30T16:45:00Z' },
  { id: 'act-004', studentId: 'std-001', type: 'quiz-complete', label: 'Completed Quiz', detail: 'Quantum Gates Quiz — 88%', timestamp: '2026-08-28T09:30:00Z' },
  { id: 'act-005', studentId: 'std-001', type: 'lesson-complete', label: 'Completed Lesson', detail: 'The CNOT Gate & Entanglement', timestamp: '2026-08-27T15:00:00Z' },
]

export const MOCK_STUDENT_DETAIL: Record<string, StudentDetail> = {
  'std-001': {
    ...MOCK_STUDENTS[0],
    courseProgress: [
      { courseId: 'crs-001', courseTitle: 'Quantum Fundamentals', completedLessons: 8, totalLessons: 8, percentage: 100, averageQuizScore: 88, lastAccessedAt: '2026-08-20T10:00:00Z' },
      { courseId: 'crs-002', courseTitle: 'Quantum Gates & Circuits', completedLessons: 10, totalLessons: 10, percentage: 100, averageQuizScore: 82, lastAccessedAt: '2026-09-01T14:23:00Z' },
      { courseId: 'crs-003', courseTitle: 'Quantum Algorithms', completedLessons: 6, totalLessons: 12, percentage: 50, averageQuizScore: 76, lastAccessedAt: '2026-08-30T16:45:00Z' },
    ],
    challengeProgress: [
      { challengeId: 'chl-001', challengeTitle: 'Create a Bell State', difficulty: 'beginner', completed: true, attempts: 2, bestScore: 92, hintsUsed: 1 },
      { challengeId: 'chl-002', challengeTitle: 'Apply the Hadamard Gate', difficulty: 'beginner', completed: true, attempts: 1, bestScore: 100, hintsUsed: 0 },
      { challengeId: 'chl-003', challengeTitle: 'Fix the Entangled Circuit', difficulty: 'intermediate', completed: false, attempts: 3, bestScore: 45, hintsUsed: 3 },
      { challengeId: 'chl-004', challengeTitle: 'Predict CNOT Output', difficulty: 'beginner', completed: true, attempts: 1, bestScore: 100, hintsUsed: 0 },
    ],
    recentActivity: ARJUN_ACTIVITIES,
  },
  'std-002': {
    ...MOCK_STUDENTS[1],
    courseProgress: [
      { courseId: 'crs-001', courseTitle: 'Quantum Fundamentals', completedLessons: 8, totalLessons: 8, percentage: 100, averageQuizScore: 96, lastAccessedAt: '2026-07-10T10:00:00Z' },
      { courseId: 'crs-002', courseTitle: 'Quantum Gates & Circuits', completedLessons: 10, totalLessons: 10, percentage: 100, averageQuizScore: 94, lastAccessedAt: '2026-08-01T10:00:00Z' },
      { courseId: 'crs-003', courseTitle: 'Quantum Algorithms', completedLessons: 12, totalLessons: 12, percentage: 100, averageQuizScore: 91, lastAccessedAt: '2026-09-01T20:10:00Z' },
    ],
    challengeProgress: [
      { challengeId: 'chl-001', challengeTitle: 'Create a Bell State', difficulty: 'beginner', completed: true, attempts: 1, bestScore: 100, hintsUsed: 0 },
      { challengeId: 'chl-002', challengeTitle: 'Apply the Hadamard Gate', difficulty: 'beginner', completed: true, attempts: 1, bestScore: 100, hintsUsed: 0 },
      { challengeId: 'chl-003', challengeTitle: 'Fix the Entangled Circuit', difficulty: 'intermediate', completed: true, attempts: 2, bestScore: 88, hintsUsed: 1 },
    ],
    recentActivity: [
      { id: 'act-p2-001', studentId: 'std-002', type: 'quiz-complete', label: 'Completed Quiz', detail: "Grover's Algorithm Quiz — 91%", timestamp: '2026-09-01T20:10:00Z' },
      { id: 'act-p2-002', studentId: 'std-002', type: 'lesson-complete', label: 'Completed Lesson', detail: "Grover's Search Algorithm", timestamp: '2026-09-01T19:30:00Z' },
    ],
  },
}

// ── Mock Courses ──────────────────────────────────────────────────────────────

export const MOCK_COURSES: InstructorCourse[] = [
  {
    id: 'crs-001',
    title: 'Quantum Fundamentals',
    description: 'Start your quantum journey — from classical bits to superposition, qubits, and the measurement postulate.',
    level: 'beginner',
    thumbnailUrl: null,
    studentsEnrolled: 248,
    completionRate: 76,
    averageQuizScore: 81,
    status: 'published',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
    lessons: [
      {
        id: 'les-001', courseId: 'crs-001', order: 1,
        title: 'Introduction to Quantum Computing',
        description: 'What is quantum computing and why does it matter?',
        learningObjectives: ['Understand classical vs quantum computing', 'Know why quantum matters'],
        theoryContent: 'Quantum computing leverages quantum mechanical phenomena such as superposition and entanglement...',
        formula: '',
        interactiveExplanation: 'Compare a classical bit with a qubit visually.',
        circuitTemplateId: null,
        quizQuestions: [],
        status: 'published',
        estimatedMinutes: 15,
        createdAt: '2026-01-10T00:00:00Z',
        updatedAt: '2026-01-10T00:00:00Z',
      },
      {
        id: 'les-002', courseId: 'crs-001', order: 2,
        title: 'Classical Bit vs Qubit',
        description: 'Deep dive into qubit states, |0⟩ and |1⟩, and probability amplitudes.',
        learningObjectives: ['Understand qubit state notation', 'Learn Dirac notation'],
        theoryContent: 'A qubit is a two-level quantum system represented as |ψ⟩ = α|0⟩ + β|1⟩...',
        formula: '|ψ⟩ = α|0⟩ + β|1⟩',
        interactiveExplanation: 'See how a qubit is described on the Bloch sphere.',
        circuitTemplateId: 'tpl-002',
        quizQuestions: [],
        status: 'published',
        estimatedMinutes: 20,
        createdAt: '2026-01-11T00:00:00Z',
        updatedAt: '2026-01-11T00:00:00Z',
      },
      {
        id: 'les-003', courseId: 'crs-001', order: 3,
        title: 'Superposition & Measurement',
        description: 'How superposition works and what happens when you measure a qubit.',
        learningObjectives: ['Understand superposition principle', 'Learn measurement collapse'],
        theoryContent: 'Superposition allows a qubit to exist in a combination of |0⟩ and |1⟩ simultaneously...',
        formula: 'H|0⟩ = (|0⟩ + |1⟩)/√2',
        interactiveExplanation: 'Apply the Hadamard gate and observe measurement outcomes.',
        circuitTemplateId: 'tpl-001',
        quizQuestions: [],
        status: 'published',
        estimatedMinutes: 25,
        createdAt: '2026-01-12T00:00:00Z',
        updatedAt: '2026-01-12T00:00:00Z',
      },
    ],
  },
  {
    id: 'crs-002',
    title: 'Quantum Gates & Circuits',
    description: 'Master single and multi-qubit gates, build circuits, and understand quantum circuit notation.',
    level: 'intermediate',
    thumbnailUrl: null,
    studentsEnrolled: 187,
    completionRate: 68,
    averageQuizScore: 74,
    status: 'published',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
    lessons: [
      {
        id: 'les-010', courseId: 'crs-002', order: 1,
        title: 'The Pauli Gates — X, Y, Z',
        description: 'Learn the fundamental single-qubit Pauli gates.',
        learningObjectives: ['Apply X, Y, Z gates', 'Understand bit and phase flip'],
        theoryContent: 'The Pauli-X gate acts as a quantum NOT gate, flipping |0⟩ to |1⟩ and vice versa...',
        formula: 'X|0⟩ = |1⟩, X|1⟩ = |0⟩',
        interactiveExplanation: 'See X gate flip a qubit in the circuit builder.',
        circuitTemplateId: null,
        quizQuestions: [],
        status: 'published',
        estimatedMinutes: 20,
        createdAt: '2026-02-01T00:00:00Z',
        updatedAt: '2026-02-01T00:00:00Z',
      },
      {
        id: 'les-011', courseId: 'crs-002', order: 2,
        title: 'The Hadamard Gate',
        description: 'The most important gate in quantum computing.',
        learningObjectives: ['Apply Hadamard gate', 'Understand superposition creation'],
        theoryContent: 'The Hadamard gate H transforms |0⟩ to |+⟩ and |1⟩ to |−⟩...',
        formula: 'H|0⟩ = |+⟩ = (|0⟩ + |1⟩)/√2',
        interactiveExplanation: 'Create superposition with H gate step by step.',
        circuitTemplateId: 'tpl-002',
        quizQuestions: [],
        status: 'published',
        estimatedMinutes: 25,
        createdAt: '2026-02-02T00:00:00Z',
        updatedAt: '2026-02-02T00:00:00Z',
      },
    ],
  },
  {
    id: 'crs-003',
    title: 'Quantum Entanglement & Bell States',
    description: 'Understand entanglement, the EPR paradox, and how to create and measure Bell states.',
    level: 'intermediate',
    thumbnailUrl: null,
    studentsEnrolled: 142,
    completionRate: 52,
    averageQuizScore: 64,
    status: 'published',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-08-25T00:00:00Z',
    lessons: [
      {
        id: 'les-020', courseId: 'crs-003', order: 1,
        title: 'Introduction to Entanglement',
        description: 'What is quantum entanglement and why Einstein called it "spooky action"?',
        learningObjectives: ['Understand entanglement concept', 'Know EPR paradox basics'],
        theoryContent: 'Quantum entanglement is a phenomenon where two qubits become correlated...',
        formula: '|Φ+⟩ = (|00⟩ + |11⟩)/√2',
        interactiveExplanation: 'Observe entangled qubits always giving correlated measurements.',
        circuitTemplateId: 'tpl-001',
        quizQuestions: [],
        status: 'published',
        estimatedMinutes: 30,
        createdAt: '2026-03-01T00:00:00Z',
        updatedAt: '2026-03-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'crs-004',
    title: 'Quantum Algorithms',
    description: "Explore Deutsch-Jozsa, Grover's search, and introductory Shor's factoring algorithm.",
    level: 'advanced',
    thumbnailUrl: null,
    studentsEnrolled: 98,
    completionRate: 38,
    averageQuizScore: 58,
    status: 'published',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-08-30T00:00:00Z',
    lessons: [],
  },
  {
    id: 'crs-005',
    title: 'Quantum Error Correction',
    description: 'Introduction to quantum noise, decoherence, and the basics of quantum error correction codes.',
    level: 'advanced',
    thumbnailUrl: null,
    studentsEnrolled: 0,
    completionRate: 0,
    averageQuizScore: 0,
    status: 'draft',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    lessons: [],
  },
]

// ── Mock Circuit Templates ────────────────────────────────────────────────────

export const MOCK_CIRCUIT_TEMPLATES: CircuitTemplate[] = [
  {
    id: 'tpl-001',
    name: 'Bell State (Φ+)',
    description: 'Creates the first Bell state — the canonical two-qubit entangled state.',
    category: 'entanglement',
    difficulty: 'beginner',
    circuit: {
      id: 'tpl-001',
      name: 'Bell State (Φ+)',
      qubits: 2,
      classicalBits: 2,
      operations: [
        { id: 'bs-h0', gate: 'H', targets: [0], moment: 0 },
        { id: 'bs-cnot', gate: 'CNOT', controls: [0], targets: [1], moment: 1 },
        { id: 'bs-m0', gate: 'MEASURE', targets: [0], classicalBit: 0, moment: 2 },
        { id: 'bs-m1', gate: 'MEASURE', targets: [1], classicalBit: 1, moment: 2 },
      ],
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    expectedResult: '50% |00⟩ + 50% |11⟩',
    educationalExplanation: 'Start with |0⟩|0⟩. Apply H to qubit 0 → superposition. Apply CNOT → entanglement. Measuring always gives correlated results: both 0 or both 1.',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'tpl-002',
    name: 'Superposition',
    description: 'Single qubit in equal superposition using the Hadamard gate.',
    category: 'superposition',
    difficulty: 'beginner',
    circuit: {
      id: 'tpl-002',
      name: 'Superposition',
      qubits: 1,
      classicalBits: 1,
      operations: [
        { id: 'sp-h0', gate: 'H', targets: [0], moment: 0 },
        { id: 'sp-m0', gate: 'MEASURE', targets: [0], classicalBit: 0, moment: 1 },
      ],
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    expectedResult: '50% |0⟩ + 50% |1⟩',
    educationalExplanation: 'H gate applied to |0⟩ creates (|0⟩+|1⟩)/√2. Measuring collapses it to 0 or 1 with equal probability.',
    createdAt: '2026-01-02T00:00:00Z',
    updatedAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 'tpl-003',
    name: 'GHZ State (3 Qubits)',
    description: 'Greenberger-Horne-Zeilinger state — maximally entangled 3-qubit state.',
    category: 'entanglement',
    difficulty: 'intermediate',
    circuit: {
      id: 'tpl-003',
      name: 'GHZ State',
      qubits: 3,
      classicalBits: 3,
      operations: [
        { id: 'ghz-h0', gate: 'H', targets: [0], moment: 0 },
        { id: 'ghz-cnot01', gate: 'CNOT', controls: [0], targets: [1], moment: 1 },
        { id: 'ghz-cnot02', gate: 'CNOT', controls: [0], targets: [2], moment: 2 },
        { id: 'ghz-m0', gate: 'MEASURE', targets: [0], classicalBit: 0, moment: 3 },
        { id: 'ghz-m1', gate: 'MEASURE', targets: [1], classicalBit: 1, moment: 3 },
        { id: 'ghz-m2', gate: 'MEASURE', targets: [2], classicalBit: 2, moment: 3 },
      ],
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    expectedResult: '50% |000⟩ + 50% |111⟩',
    educationalExplanation: 'Extend the Bell state to 3 qubits. All three are perfectly correlated — measuring any one determines all others.',
    createdAt: '2026-01-03T00:00:00Z',
    updatedAt: '2026-01-03T00:00:00Z',
  },
  {
    id: 'tpl-004',
    name: 'Phase Kickback',
    description: 'Demonstrates quantum phase kickback — the control qubit acquires a phase.',
    category: 'gates',
    difficulty: 'intermediate',
    circuit: {
      id: 'tpl-004',
      name: 'Phase Kickback',
      qubits: 2,
      classicalBits: 2,
      operations: [
        { id: 'pk-h0', gate: 'H', targets: [0], moment: 0 },
        { id: 'pk-x1', gate: 'X', targets: [1], moment: 0 },
        { id: 'pk-cnot', gate: 'CNOT', controls: [0], targets: [1], moment: 1 },
        { id: 'pk-h0b', gate: 'H', targets: [0], moment: 2 },
        { id: 'pk-m0', gate: 'MEASURE', targets: [0], classicalBit: 0, moment: 3 },
        { id: 'pk-m1', gate: 'MEASURE', targets: [1], classicalBit: 1, moment: 3 },
      ],
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    expectedResult: '100% |11⟩',
    educationalExplanation: 'Phase kickback occurs when the target is in an eigenstate. The phase is "kicked back" to the control qubit — fundamental to Grover and Shor.',
    createdAt: '2026-01-04T00:00:00Z',
    updatedAt: '2026-01-04T00:00:00Z',
  },
  {
    id: 'tpl-005',
    name: 'Quantum NOT (X Gate)',
    description: 'Simple Pauli-X gate flipping a qubit from |0⟩ to |1⟩.',
    category: 'gates',
    difficulty: 'beginner',
    circuit: {
      id: 'tpl-005',
      name: 'Quantum NOT',
      qubits: 1,
      classicalBits: 1,
      operations: [
        { id: 'not-x0', gate: 'X', targets: [0], moment: 0 },
        { id: 'not-m0', gate: 'MEASURE', targets: [0], classicalBit: 0, moment: 1 },
      ],
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    expectedResult: '100% |1⟩',
    educationalExplanation: 'The X gate (Pauli-X) is the quantum analogue of classical NOT. It flips |0⟩ → |1⟩ and |1⟩ → |0⟩.',
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-01-05T00:00:00Z',
  },
]

// ── Mock Challenges ───────────────────────────────────────────────────────────

export const MOCK_CHALLENGES: InstructorChallenge[] = [
  {
    id: 'chl-001',
    title: 'Create a Bell State',
    description: 'Build a quantum circuit that creates the first Bell state (Φ+).',
    objective: 'Construct a circuit that produces 50% |00⟩ and 50% |11⟩ measurement outcomes.',
    type: 'build-circuit',
    difficulty: 'beginner',
    starterCircuitId: null,
    validationConfig: {
      expectedProbabilities: { '00': 0.5, '11': 0.5 },
      probabilityTolerance: 0.05,
      requiredGates: ['H', 'CNOT'],
      explanation: 'Apply H to qubit 0, then CNOT with qubit 0 as control and qubit 1 as target.',
    },
    hints: [
      { order: 1, text: 'Start by placing a gate on the first qubit.' },
      { order: 2, text: 'Which gate creates superposition from |0⟩?' },
      { order: 3, text: 'Apply a Hadamard (H) gate to qubit 0, then use CNOT with qubit 0 as control.' },
    ],
    totalAttempts: 342,
    completionRate: 84,
    averageAttempts: 1.8,
    hintsUsedRate: 42,
    status: 'published',
    estimatedMinutes: 15,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    id: 'chl-002',
    title: 'Apply the Hadamard Gate',
    description: 'Create a single-qubit superposition using the Hadamard gate.',
    objective: 'Build a circuit that gives 50% |0⟩ and 50% |1⟩.',
    type: 'build-circuit',
    difficulty: 'beginner',
    starterCircuitId: null,
    validationConfig: {
      expectedProbabilities: { '0': 0.5, '1': 0.5 },
      probabilityTolerance: 0.05,
      requiredGates: ['H'],
      explanation: 'The Hadamard gate H transforms |0⟩ into equal superposition.',
    },
    hints: [
      { order: 1, text: 'You only need one gate for this challenge.' },
      { order: 2, text: 'Look for the gate labeled H in the palette.' },
      { order: 3, text: 'Drag or click the H gate onto qubit 0.' },
    ],
    totalAttempts: 412,
    completionRate: 96,
    averageAttempts: 1.2,
    hintsUsedRate: 18,
    status: 'published',
    estimatedMinutes: 10,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-08-10T00:00:00Z',
  },
  {
    id: 'chl-003',
    title: 'Fix the Entangled Circuit',
    description: 'A broken entanglement circuit is given. Identify and fix the error.',
    objective: 'Repair the circuit so it correctly produces the Bell state.',
    type: 'fix-circuit',
    difficulty: 'intermediate',
    starterCircuitId: 'tpl-001',
    validationConfig: {
      expectedProbabilities: { '00': 0.5, '11': 0.5 },
      probabilityTolerance: 0.05,
      requiredGates: ['H', 'CNOT'],
      explanation: 'The control and target qubits of the CNOT were swapped. CNOT should have qubit 0 as control and qubit 1 as target.',
    },
    hints: [
      { order: 1, text: 'Run the simulation and observe what output you get.' },
      { order: 2, text: 'The CNOT gate is the problem. Check which qubit is control vs target.' },
      { order: 3, text: 'Remove and re-add the CNOT gate: control on qubit 0, target on qubit 1.' },
    ],
    totalAttempts: 198,
    completionRate: 52,
    averageAttempts: 3.4,
    hintsUsedRate: 71,
    status: 'published',
    estimatedMinutes: 20,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'chl-004',
    title: 'Predict CNOT Output',
    description: 'Given a circuit with CNOT, predict the measurement outcome.',
    objective: 'Select the correct output state for the given input and CNOT configuration.',
    type: 'predict-output',
    difficulty: 'beginner',
    starterCircuitId: null,
    validationConfig: {
      expectedProbabilities: { '11': 1.0 },
      probabilityTolerance: 0,
      requiredGates: [],
      explanation: 'X gate flips qubit 0 to |1⟩. CNOT with |1⟩ control flips qubit 1 to |1⟩. Result: |11⟩.',
    },
    hints: [
      { order: 1, text: 'Trace the circuit from left to right, one gate at a time.' },
      { order: 2, text: 'After X gate on qubit 0, what is the state of qubit 0?' },
      { order: 3, text: 'Qubit 0 is |1⟩. A CNOT with control |1⟩ flips the target qubit.' },
    ],
    totalAttempts: 287,
    completionRate: 89,
    averageAttempts: 1.4,
    hintsUsedRate: 24,
    status: 'published',
    estimatedMinutes: 10,
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-08-05T00:00:00Z',
  },
  {
    id: 'chl-005',
    title: "Grover's 2-Qubit Search",
    description: 'Implement a simplified 2-qubit Grover search to find the marked state |11⟩.',
    objective: "Build Grover's oracle and diffuser for 2 qubits.",
    type: 'algorithm',
    difficulty: 'advanced',
    starterCircuitId: null,
    validationConfig: {
      expectedProbabilities: { '11': 1.0 },
      probabilityTolerance: 0.1,
      requiredGates: ['H', 'CNOT', 'Z'],
      explanation: "Grover's algorithm amplifies the amplitude of the target state through oracle + diffusion.",
    },
    hints: [
      { order: 1, text: 'Start with uniform superposition: apply H to all qubits.' },
      { order: 2, text: 'The oracle for |11⟩ uses a CZ (controlled-Z) gate.' },
      { order: 3, text: 'The diffuser is H·X·CZ·X·H on both qubits. After one iteration, |11⟩ probability approaches 1.' },
    ],
    totalAttempts: 87,
    completionRate: 28,
    averageAttempts: 5.1,
    hintsUsedRate: 88,
    status: 'published',
    estimatedMinutes: 45,
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-08-28T00:00:00Z',
  },
]

// ── Mock Assessments ──────────────────────────────────────────────────────────

const QUANTUM_GATES_QUESTIONS: InstructorQuizQuestion[] = [
  {
    id: 'q-001', assessmentId: 'asmnt-001', type: 'multiple-choice',
    prompt: 'Which quantum gate transforms |0⟩ into |1⟩ and |1⟩ into |0⟩?',
    options: [
      { id: 'a', label: 'H (Hadamard)' },
      { id: 'b', label: 'X (Pauli-X)' },
      { id: 'c', label: 'Z (Pauli-Z)' },
      { id: 'd', label: 'CNOT' },
    ],
    correctOptionId: 'b',
    explanation: 'The Pauli-X gate acts as a quantum NOT gate, flipping |0⟩ to |1⟩ and |1⟩ to |0⟩.',
    relatedConcept: 'Quantum Gates',
    averageScore: 88,
    attemptCount: 187,
  },
  {
    id: 'q-002', assessmentId: 'asmnt-001', type: 'multiple-choice',
    prompt: 'What is the output state when a Hadamard gate is applied to |0⟩?',
    options: [
      { id: 'a', label: '|0⟩' },
      { id: 'b', label: '|1⟩' },
      { id: 'c', label: '(|0⟩ + |1⟩)/√2' },
      { id: 'd', label: '(|0⟩ - |1⟩)/√2' },
    ],
    correctOptionId: 'c',
    explanation: 'H|0⟩ = (|0⟩ + |1⟩)/√2, which is the |+⟩ state — equal superposition.',
    relatedConcept: 'Superposition',
    averageScore: 82,
    attemptCount: 187,
  },
  {
    id: 'q-003', assessmentId: 'asmnt-001', type: 'true-false',
    prompt: 'The CNOT gate requires two qubits — a control qubit and a target qubit.',
    options: [
      { id: 'true', label: 'True' },
      { id: 'false', label: 'False' },
    ],
    correctOptionId: 'true',
    explanation: 'CNOT (Controlled-NOT) applies X to the target qubit only when the control qubit is |1⟩.',
    relatedConcept: 'Quantum Gates',
    averageScore: 94,
    attemptCount: 187,
  },
  {
    id: 'q-004', assessmentId: 'asmnt-001', type: 'output-prediction',
    prompt: 'Given input |00⟩, circuit H on q0 → CNOT(q0→q1) → MEASURE. What is the most likely output?',
    options: [
      { id: 'a', label: 'Always |00⟩' },
      { id: 'b', label: 'Always |11⟩' },
      { id: 'c', label: '50% |00⟩ and 50% |11⟩' },
      { id: 'd', label: '50% |01⟩ and 50% |10⟩' },
    ],
    correctOptionId: 'c',
    explanation: 'H creates superposition on q0. CNOT entangles q1 with q0. Measurement gives |00⟩ or |11⟩ with equal probability.',
    relatedConcept: 'Bell States',
    averageScore: 71,
    attemptCount: 187,
  },
]

export const MOCK_ASSESSMENTS: InstructorAssessment[] = [
  {
    id: 'asmnt-001',
    title: 'Quantum Gates & Superposition Quiz',
    relatedCourseId: 'crs-002',
    relatedConcept: 'Quantum Gates',
    questions: QUANTUM_GATES_QUESTIONS,
    averageScore: 82,
    totalAttempts: 187,
    successRate: 78,
    status: 'published',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-08-10T00:00:00Z',
  },
  {
    id: 'asmnt-002',
    title: 'Entanglement & Bell States Quiz',
    relatedCourseId: 'crs-003',
    relatedConcept: 'Entanglement',
    questions: [],
    averageScore: 64,
    totalAttempts: 142,
    successRate: 58,
    status: 'published',
    createdAt: '2026-03-10T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'asmnt-003',
    title: 'Quantum Fundamentals Assessment',
    relatedCourseId: 'crs-001',
    relatedConcept: 'Quantum Fundamentals',
    questions: [],
    averageScore: 81,
    totalAttempts: 248,
    successRate: 82,
    status: 'published',
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-07-15T00:00:00Z',
  },
  {
    id: 'asmnt-004',
    title: 'Quantum Algorithms Mid-Term',
    relatedCourseId: 'crs-004',
    relatedConcept: "Grover's Algorithm",
    questions: [],
    averageScore: 58,
    totalAttempts: 98,
    successRate: 45,
    status: 'draft',
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-08-30T00:00:00Z',
  },
]

// ── Mock Announcements ────────────────────────────────────────────────────────

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-001',
    title: 'New Challenge: Build a GHZ State!',
    message: 'We just released a new 3-qubit entanglement challenge. Try to create the Greenberger-Horne-Zeilinger state. Hints available if you get stuck!',
    targetType: 'all',
    targetCourseId: null,
    targetStudentIds: [],
    status: 'published',
    publishDate: '2026-09-01T09:00:00Z',
    createdAt: '2026-08-31T14:00:00Z',
    updatedAt: '2026-09-01T09:00:00Z',
  },
  {
    id: 'ann-002',
    title: 'Quantum Algorithms Course Update',
    message: "We've added 3 new lessons to the Quantum Algorithms course covering the Quantum Fourier Transform. Make sure to check your progress dashboard!",
    targetType: 'course',
    targetCourseId: 'crs-004',
    targetStudentIds: [],
    status: 'published',
    publishDate: '2026-08-25T10:00:00Z',
    createdAt: '2026-08-24T16:00:00Z',
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'ann-003',
    title: 'Live Q&A Session: Entanglement Deep Dive',
    message: 'Join us this Friday at 6pm IST for a live Q&A session on quantum entanglement and Bell states. Submit your questions in advance!',
    targetType: 'all',
    targetCourseId: null,
    targetStudentIds: [],
    status: 'published',
    publishDate: '2026-08-20T08:00:00Z',
    createdAt: '2026-08-19T12:00:00Z',
    updatedAt: '2026-08-20T08:00:00Z',
  },
  {
    id: 'ann-004',
    title: 'Platform Maintenance Window',
    message: 'SankalpQ will be under maintenance on Sunday Sept 5 from 2-4am IST. All progress is saved automatically.',
    targetType: 'all',
    targetCourseId: null,
    targetStudentIds: [],
    status: 'draft',
    publishDate: '2026-09-04T20:00:00Z',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
]

// ── Mock Analytics ────────────────────────────────────────────────────────────

export const MOCK_ANALYTICS: PlatformAnalytics = {
  totalStudents: 248,
  activeStudents: 187,
  totalCourses: 5,
  activeChallenges: 18,
  averageCourseCompletion: 59,
  averageQuizScore: 74,
  studentGrowth: [
    { month: 'Apr', students: 42 },
    { month: 'May', students: 78 },
    { month: 'Jun', students: 124 },
    { month: 'Jul', students: 178 },
    { month: 'Aug', students: 224 },
    { month: 'Sep', students: 248 },
  ],
  courseAnalytics: [
    { courseId: 'crs-001', courseTitle: 'Quantum Fundamentals', enrolled: 248, completionRate: 76, averageQuizScore: 81, averageTimeMinutes: 82, engagementScore: 88 },
    { courseId: 'crs-002', courseTitle: 'Quantum Gates & Circuits', enrolled: 187, completionRate: 68, averageQuizScore: 74, averageTimeMinutes: 94, engagementScore: 79 },
    { courseId: 'crs-003', courseTitle: 'Entanglement & Bell States', enrolled: 142, completionRate: 52, averageQuizScore: 64, averageTimeMinutes: 110, engagementScore: 65 },
    { courseId: 'crs-004', courseTitle: 'Quantum Algorithms', enrolled: 98, completionRate: 38, averageQuizScore: 58, averageTimeMinutes: 145, engagementScore: 52 },
    { courseId: 'crs-005', courseTitle: 'Quantum Error Correction', enrolled: 0, completionRate: 0, averageQuizScore: 0, averageTimeMinutes: 0, engagementScore: 0 },
  ],
  challengeAnalytics: [
    { challengeId: 'chl-001', challengeTitle: 'Create a Bell State', difficulty: 'beginner', totalAttempts: 342, completionRate: 84, averageAttempts: 1.8, hintsUsedRate: 42 },
    { challengeId: 'chl-002', challengeTitle: 'Apply the Hadamard Gate', difficulty: 'beginner', totalAttempts: 412, completionRate: 96, averageAttempts: 1.2, hintsUsedRate: 18 },
    { challengeId: 'chl-003', challengeTitle: 'Fix the Entangled Circuit', difficulty: 'intermediate', totalAttempts: 198, completionRate: 52, averageAttempts: 3.4, hintsUsedRate: 71 },
    { challengeId: 'chl-004', challengeTitle: 'Predict CNOT Output', difficulty: 'beginner', totalAttempts: 287, completionRate: 89, averageAttempts: 1.4, hintsUsedRate: 24 },
    { challengeId: 'chl-005', challengeTitle: "Grover's 2-Qubit Search", difficulty: 'advanced', totalAttempts: 87, completionRate: 28, averageAttempts: 5.1, hintsUsedRate: 88 },
  ],
  conceptDifficulty: [
    { concept: "Grover's Algorithm", strugglingPercentage: 55, totalStudents: 98, averageScore: 48 },
    { concept: 'Entanglement', strugglingPercentage: 42, totalStudents: 248, averageScore: 58 },
    { concept: 'Multi-Qubit Circuits', strugglingPercentage: 38, totalStudents: 187, averageScore: 62 },
    { concept: 'Phase Kickback', strugglingPercentage: 31, totalStudents: 142, averageScore: 67 },
    { concept: 'Bell States', strugglingPercentage: 28, totalStudents: 187, averageScore: 64 },
    { concept: 'CNOT Gate', strugglingPercentage: 22, totalStudents: 248, averageScore: 71 },
    { concept: 'Superposition', strugglingPercentage: 14, totalStudents: 248, averageScore: 82 },
    { concept: 'Quantum Gates', strugglingPercentage: 11, totalStudents: 248, averageScore: 85 },
  ],
}

// ── Mock AI Insights ──────────────────────────────────────────────────────────

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ins-001',
    type: 'concept-struggle',
    priority: 'high',
    title: 'Entanglement Concept Gap Detected',
    message: '42% of active students are struggling with Entanglement. Most incorrect challenge attempts involve CNOT control-vs-target selection. Quiz scores in this topic are 16 points below the platform average.',
    recommendation: 'Assign the Bell State interactive circuit exercise to all students enrolled in "Quantum Gates & Circuits". Consider adding a visual explainer lesson on control vs target qubit semantics.',
    affectedStudentCount: 78,
    relatedConceptOrCourse: 'Entanglement',
    generatedAt: '2026-09-01T06:00:00Z',
  },
  {
    id: 'ins-002',
    type: 'positive-trend',
    priority: 'low',
    title: 'Superposition Lesson Improving Challenge Scores',
    message: 'Students who completed the interactive Superposition lesson (with circuit builder exercise) scored an average of 23% higher on Bell State challenges than those who skipped it.',
    recommendation: 'Make the Superposition interactive circuit exercise mandatory before unlocking the Bell State challenge. Track this improvement to validate the correlation.',
    affectedStudentCount: 134,
    relatedConceptOrCourse: 'Superposition',
    generatedAt: '2026-09-01T06:00:00Z',
  },
  {
    id: 'ins-003',
    type: 'student-at-risk',
    priority: 'high',
    title: '12 Students Haven\'t Logged In for 7+ Days',
    message: '12 students with incomplete course progress haven\'t accessed SankalpQ in over a week. Their average quiz score is 41%, significantly below the platform average of 74%.',
    recommendation: 'Publish a targeted announcement to re-engage these students. Consider offering a simplified "Quick Start" challenge with lower difficulty to rebuild confidence.',
    affectedStudentCount: 12,
    relatedConceptOrCourse: 'Platform Engagement',
    generatedAt: '2026-09-01T06:00:00Z',
  },
  {
    id: 'ins-004',
    type: 'course-improvement',
    priority: 'medium',
    title: "Quantum Algorithms Course Has Low Completion Rate",
    message: 'The Quantum Algorithms course has the lowest completion rate (38%) and average quiz score (58%). Drop-off is highest at the Grover\'s Algorithm lesson — 55% of students attempting this lesson do not complete it.',
    recommendation: "Add a prerequisite checkpoint for Quantum Algorithms. Create a short 'Grover Intuition' explainer lesson before the full Grover lesson, including a simplified 2-qubit example.",
    affectedStudentCount: 60,
    relatedConceptOrCourse: 'Quantum Algorithms',
    generatedAt: '2026-09-01T06:00:00Z',
  },
  {
    id: 'ins-005',
    type: 'challenge-recommendation',
    priority: 'medium',
    title: 'Circuit Challenge Completion Correlates with Lesson Order',
    message: "Students who attempted 'Fix the Entangled Circuit' before completing the Entanglement lesson had a 28% success rate vs 74% for those who completed the lesson first.",
    recommendation: "Add a lesson prerequisite gate to 'Fix the Entangled Circuit'. Enforce completion of at least one Entanglement lesson before the challenge unlocks.",
    affectedStudentCount: 45,
    relatedConceptOrCourse: 'Fix the Entangled Circuit',
    generatedAt: '2026-09-01T06:00:00Z',
  },
]
